services:
  - type: web
    name: sytem-dark
    env: node
    plan: free
    buildCommand: npm install --omit=dev --no-audit --no-fund
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PREFIX
        value: .
      - key: BOT_NAME
        value: Sytem DARK
      - key: OWNER_NAME
        value: Dark Net
      - key: OWNER_NUMBER
        value: 244945280380
      - key: BOT_NUMBER
        value: 244949926074
      - key: PAIRING_NUMBER
        value: 244949926074
      - key: PAIRING_CODE
        value: true
      - key: USE_QR
        value: false
      - key: MONGODB_DB
        value: sytem_dark
      - key: AUTH_ID
        value: sytem_dark_244949926074
      - key: AUTH_DIR
        value: ./dono/sytem-dark-session
      - key: CONNECT_TIMEOUT_MS
        value: 180000
      - key: DEFAULT_QUERY_TIMEOUT_MS
        value: 90000
